{% set name = "transformers" %}
{% set version = "4.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e151ee7a56e7649de567ad6f4d6a83245c564ca93a886ef0e025f058895cf9cc

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy
    - requests
    - tqdm >=4.27
    - tokenizers ==0.9.4
    - dataclasses
    - packaging
    - filelock
    - regex !=2019.12.17
    - sacremoses

test:
  imports:
    - transformers
  commands:
    - transformers-cli --help

about:
  home: https://github.com/huggingface/transformers
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: State-of-the-art Natural Language Processing for TensorFlow 2.0 and PyTorch
  doc_url: https://huggingface.co/transformers/

extra:
  recipe-maintainers:
    - roccqqck
    - oblute
    - rluria14
    - ndmaxar
    - setu4993
    - hadim
